### PR TITLE
Added Pixel and Threshold Attack

### LINKED ISSUE #280: Request for addition of Few Pixel Attack (One Pixel Attack)
I would like to add an implementation of Few Pixel Attack (https://arxiv.org/pdf/1906.06026.pdf) which is a generalisation of One Pixel Attack (https://arxiv.org/pdf/1710.08864.pdf).

### PR DESCRIPTION
**Pull request by shashankkotyan**
# Description
Added implementation of Few-Pixel and Threshold Attack. 
Requires pycma (https://github.com/CMA-ES/pycma) library. 

Resolves #280  and #281 

## Type of change
- [x] Bug fix (non-breaking)
- [x] New feature (non-breaking)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Testing
Tested Pixel and Threshold on the CIFAR-10 dataset across Keras and TensorflowV2 platforms. 

- [x] Pixel Attack with DE optimisation on Keras Classifier
- [x] Threshold Attack with DE optimisation on Keras Classifier
- [x] Pixel Attack with CMA-ES optimisation on Keras Classifier
- [x] Threshold Attack with CMA-ES optimisation on Keras Classifier
- [x] Pixel Attack with DE optimisation on TesnorflowV2 Classifier
- [x] Threshold Attack with DE optimisation on TesnorflowV2 Classifier
- [x] Pixel Attack with CMA-ES optimisation on TesnorflowV2 Classifier
- [x] Threshold Attack with CMA-ES optimisation on TesnorflowV2 Classifier

**Test Configuration**:
- OS Ubuntu 18.04
- Python version 3.7
- ART version 1.1.0 on dev 1.2.0 branch
- TensorFlowV2 2.1.0
- Keras 2.2.3 with Tensorflow 1.13.1

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by beat-buesser** [comment]
Hi @shashankkotyan Thank you for your first pull request to ART! We will start reviewing it as soon as possible.

**Comment by beat-buesser** [comment]
@shashankkotyan I had a quick look at your code which is in good shape. After an initial review, could you please take look at the three items below:

- take a look at our PEP8 check on Travis CI (https://travis-ci.org/IBM/adversarial-robustness-toolbox/jobs/646303454?utm_medium=notification&utm_source=github_status) and fix the PEP8 warnings
- add the names and references of your attacks to the `README.md` and README-cn.md in the section `Evasion Attacks`
- add a few quickly running unit tests for each of the new attacks

**Comment by shashankkotyan** [comment]
Hi @beat-buesser, I am not sure what happened but DCO test was unsuccessful. 
I opened up details and saw two git commands. I ran and now I am seeing commits from you too. 
Is it normal to happen?

Apologies but I am new to these kinds of tests.

**Comment by shashankkotyan** [comment]
Hi @beat-buesser, I am not sure what happened but DCO test was unsuccessful. 
I opened up details and saw two git commands. I ran and now I am seeing commits from you too. 
Is it normal to happen?

Apologies but I am new to these kinds of tests.

**Comment by beat-buesser** [comment]
@shashankkotyan No worries, everything can be fixed. The force-push solution for DCO should only be used if you have forgotten to sign-off your most recent commits as it seems to sign also unrelated commits. Try to use the `git commit -s` option or the corresponding settings in your IDE when creating commits to sign the commits locally.

I would recommend to make a separate checkout of your remote repo (`git clone`) to not overwrite your main checkout. There create a new local branch off your local `dev_1.2.0`, called for example `dev_1.2.0_fix`, reset this new local branch `dev_1.2.0_fix` to the last commit before unintentionally signed unrelated commits (ef972ac6fa2bfd74f18038e52463d7e009acbed9), and finally `git cherry-pick` the 10 commits belonging to you from `dev_1.2.0` to `dev_1.2.0_fix` and force push `dev_1.2.0_fix` to your remote `dev_1.2.0`.

**Comment by shashankkotyan** [comment]
Not sure what happened here. I will create a pull request. I reset my commit before unintentional commit but there was still the unrelated commits. 

I will open a new PR, apologies for the inconvenience caused.

**Comment by beat-buesser** [comment]
Ok, no worries, we'll continue on the new pull request.

**Pull request closed without merging**
